### ISSUE TITLE
ValueError when using Django (1.8)

### ISSUE THREAD

**Issue by zhengzhou1992** [DheerendraRathor/ldap-oauth2#9]
Hi Dheerendra,

Newly installed according to [Installation Guidelines](https://github.com/DheerendraRathor/ldap-oauth2/blob/master/INSTALLATION.md), when I open the root URL in my browser, HTTP 500 respond, below is the Traceback:

#( 04/17/17@ 1:40PM )( ubuntu@ubuntu ):/tmp/venv_test/ldap-oauth2@master✔
   python manage.py runserver 0.0.0.0:7777       
Performing system checks...

System check identified no issues (0 silenced).
April 17, 2017 - 11:10:45
Django version 1.8, using settings 'sso.settings'
Starting development server at http://0.0.0.0:7777/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 268, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/defaults.py", line 45, in server_error
    return http.HttpResponseServerError(template.render())
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/templatetags/static.py", line 105, in render
    url = self.url(context)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 16, in url
    return static(path)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'sso/css/bootstrap.min.css' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x7fd5a960bdd0>.
[17/Apr/2017 11:11:10]"GET /account/login/ HTTP/1.1" 500 59

**Comment by DheerendraRathor** [comment]
did you run `python manage.py collectstatic`? Run it before doing `runserver`.
